module.exports = [
  "/es/",
  {
    title: "Guía Completa",
    path: "/es/apostila/",
    collapsable: true,
    children: [
      "/es/apostila/1.-estrutura-de-contratos-inteligentes.md",
      "/es/apostila/2.-tipos-de-variaveis.md",
      "/es/apostila/3.-funcoes.md",
      "/es/apostila/4.-modificadores-de-funcoes-view-pure-constant.md",
      "/es/apostila/5.-visibilidade-de-funcoes-external-public-internal-and-private.md",
      "/es/apostila/6.-visibilidade-de-variaveis-external-public-internal-and-private.md",
      "/es/apostila/7.-variaveis-built-in-msg.sender-msg.value....md",
      "/es/apostila/8.-arrays-listas.md",
      "/es/apostila/9.-controladores-de-fluxo-if-for-while.md",
      "/es/apostila/10.-mappings-dicionarios.md",
      "/es/apostila/11.-struct.md",
      "/es/apostila/12.-enums.md",
      "/es/apostila/13.-memory-vs-storage.md",
      "/es/apostila/14.-eventos.md",
      "/es/apostila/15.-modificadores.md",
      "/es/apostila/16.-constructor.md",
      "/es/apostila/17.-funcoes-pagaveis-function-payable.md",
      "/es/apostila/18.-interagindo-com-outro-contrato.md",
      "/es/apostila/19.-criando-contratos-a-partir-de-um-contrato..md",
      "/es/apostila/20.-erros.md",
      {
        title: "Extra (Avanzado)",
        path: "/es/apostila/extra-avancado/",
        children: [
          "/es/apostila/extra-avancado/21.-fallback-functions.md",
          "/es/apostila/extra-avancado/22.-assembly.md",
          "/es/apostila/extra-avancado/23.-bibliotecas-librarys.md",
          "/es/apostila/extra-avancado/24.-heranca.md",
        ],
      },
    ],
  },
  {
    title: "Ejemplos",
    path: "/es/exemplos/",
    collapsable: true,
    children: [
      "/es/exemplos/",
      {
        title: "Linguagem (v0.8.3)",
        path: "/es/exemplos/linguagem-v0.8.3/",
        children: [
          "/es/exemplos/linguagem-v0.8.3/",
          "/es/exemplos/linguagem-v0.8.3/ola-mundo.md",
          "/es/exemplos/linguagem-v0.8.3/primeira-aplicacao.md",
          "/es/exemplos/linguagem-v0.8.3/tipos-de-dados-primarios.md",
          "/es/exemplos/linguagem-v0.8.3/variaveis.md",
          "/es/exemplos/linguagem-v0.8.3/constantes.md",
          "/es/exemplos/linguagem-v0.8.3/imutaveis.md",
          "/es/exemplos/linguagem-v0.8.3/lendo-e-escrevendo-para-uma-variavel-de-estado.md",
          "/es/exemplos/linguagem-v0.8.3/ether-e-wei.md",
          "/es/exemplos/linguagem-v0.8.3/gas.md",
          "/es/exemplos/linguagem-v0.8.3/if-else.md",
          "/es/exemplos/linguagem-v0.8.3/for-e-while-loop.md",
          "/es/exemplos/linguagem-v0.8.3/mapping.md",
          "/es/exemplos/linguagem-v0.8.3/matriz.md",
          "/es/exemplos/linguagem-v0.8.3/enum.md",
          "/es/exemplos/linguagem-v0.8.3/structs.md",
          "/es/exemplos/linguagem-v0.8.3/localizacoes-de-dados-armazenamento-memoria-e-calldata.md",
          "/es/exemplos/linguagem-v0.8.3/funcao.md",
          "/es/exemplos/linguagem-v0.8.3/funcoes-view-e-pure.md",
          "/es/exemplos/linguagem-v0.8.3/erro.md",
          "/es/exemplos/linguagem-v0.8.3/modificador-de-funcao.md",
          "/es/exemplos/linguagem-v0.8.3/eventos.md",
          "/es/exemplos/linguagem-v0.8.3/constructor.md",
          "/es/exemplos/linguagem-v0.8.3/heranca.md",
          "/es/exemplos/linguagem-v0.8.3/sombreamento-de-variaveis-de-estado-herdadas.md",
          "/es/exemplos/linguagem-v0.8.3/chamando-contratos-de-classe-pai.md",
          "/es/exemplos/linguagem-v0.8.3/visibilidade.md",
          "/es/exemplos/linguagem-v0.8.3/interface.md",
          "/es/exemplos/linguagem-v0.8.3/pagavel.md",
          "/es/exemplos/linguagem-v0.8.3/enviando-ether-transferir-enviar-chamar.md",
          "/es/exemplos/linguagem-v0.8.3/fallback.md",
          "/es/exemplos/linguagem-v0.8.3/call.md",
          "/es/exemplos/linguagem-v0.8.3/delegatecall.md",
          "/es/exemplos/linguagem-v0.8.3/seletor-de-funcao.md",
          "/es/exemplos/linguagem-v0.8.3/chamando-outro-contrato.md",
          "/es/exemplos/linguagem-v0.8.3/contrato-que-cria-outros-contratos.md",
          "/es/exemplos/linguagem-v0.8.3/try-catch.md",
          "/es/exemplos/linguagem-v0.8.3/import.md",
          "/es/exemplos/linguagem-v0.8.3/biblioteca.md",
          "/es/exemplos/linguagem-v0.8.3/hashing-with-keccak256.md",
          "/es/exemplos/linguagem-v0.8.3/verificando-assinatura.md"
        ],
      },
      {
        title: "Aplicaciones",
        path: "/es/exemplos/aplicacoes/",
        children: [
          "/es/exemplos/aplicacoes/carteira-multi-assinaturas.md",
          "/es/exemplos/aplicacoes/arvore-de-merkle.md",
          "/es/exemplos/aplicacoes/mapping-iteravel",
          "/es/exemplos/aplicacoes/erc20.md",
          "/es/exemplos/aplicacoes/endereco-de-contrato-pre-computado-com-create2.md",
          "/es/exemplos/aplicacoes/contrato-proxy-minimo.md",
          "/es/exemplos/aplicacoes/implante-qualquer-contrato.md",
          "/es/exemplos/aplicacoes/canal-de-pagamento-unidirecional.md",
          "/es/exemplos/aplicacoes/canal-de-pagamento-bidirecional.md",
          "/es/exemplos/aplicacoes/leilao-ingles.md",
          "/es/exemplos/aplicacoes/leilao-holandes.md",
        ],
      },
      {
        title: "Hacks",
        path: "/es/exemplos/hacks/",
        children: [
          "/es/exemplos/hacks/",
          "/es/exemplos/hacks/reentrada.md",
          "/es/exemplos/hacks/overflow-e-underflow-aritmeticos.md",
          "/es/exemplos/hacks/autodestruicao.md",
          "/es/exemplos/hacks/acessando-dados-privados.md",
          "/es/exemplos/hacks/delegatecall.md",
          "/es/exemplos/hacks/fonte-de-aleatoriedade.md",
          "/es/exemplos/hacks/recusa-de-servico.md",
          "/es/exemplos/hacks/phishing-com-tx.origin.md",
          "/es/exemplos/hacks/escondendo-codigos-maliciosos-com-contrato-externo.md",
          "/es/exemplos/hacks/honeypot.md",
          "/es/exemplos/hacks/front-running.md",
          "/es/exemplos/hacks/manipulacao-do-bloco-timestamp.md",
          "/es/exemplos/hacks/repeticao-de-assinatura.md",
          "/es/exemplos/hacks/ignorar-a-verificacao-do-tamanho-do-contrato.md",
        ],
      },
      {
        title: "DeFi",
        path: "/es/exemplos/defi/",
        children: [
          "/es/exemplos/defi/",
          "/es/exemplos/defi/exemplos-de-uniswap-v2.md",
          "/es/exemplos/defi/oraculo-de-preco-da-chainlink.md",
          "/es/exemplos/defi/recompensas-de-aposta.md",
        ],
      },
    ],
  },
  {
    title: "EVM Máquina Virtual Ethereum",
    path: "/es/evm-maquina-virtual-ethereum/",
    children: [
      "/es/evm-maquina-virtual-ethereum/accounts.md",
      "/es/evm-maquina-virtual-ethereum/transactions.md",
      "/es/evm-maquina-virtual-ethereum/gas-taxas.md",
      "/es/evm-maquina-virtual-ethereum/op_codes.md",
      "/es/evm-maquina-virtual-ethereum/bytecodes.md",
      {
        title: "Patterns and Standards",
        path: "/es/evm-maquina-virtual-ethereum/patterns-and-standards",
        children: ["/es/evm-maquina-virtual-ethereum/patterns-and-standards/erc20-and-eip-20.md"],
      },
    ],
  },
  {
    title: "Seguridad",
    path: "/es/seguranca/",
    children: [
      {
        title: "Vulnerabilidades Conocidas",
        path: "/es/seguranca/vulnerabilidades-conhecidas/",
        children: [
          "/es/seguranca/vulnerabilidades-conhecidas/funcao-de-re-entrada-reetrancy.md",
          "/es/seguranca/vulnerabilidades-conhecidas/overflow-e-underflow-aritmetico.md",
        ],
      },
    ],
  },
]
